#This means: "Run this workflow when code is pushed to the main branch

#runs-on: ubuntu-latest means GitHub spins up a Linux server to run your commands.
   

name: CI

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build